In [4]:
import sys
import os
import pandas as pd
import numpy as np
sys.path.append(os.path.dirname(os.getcwd()))
import functions.process as proc
from scipy.stats.contingency import crosstab

In [2]:
y = pd.Series([0,0,0,1,1,1,2,2,2,2,2,3,3,4,4,4,4,0,0,2,2,2,4,3,3,3,3])
onoff, dur, transi = proc.onoff_dict(y, labels =np.unique(y), return_duration=True, return_transitions=True)

onoff, dur, transi

({0: [(0, 3), (17, 2)],
  1: [(3, 3)],
  2: [(6, 5), (19, 3)],
  3: [(11, 2), (23, 4)],
  4: [(13, 4), (22, 1)]},
 array([3, 3, 5, 2, 4, 2, 3, 1, 4]),
 array([0, 1, 2, 3, 4, 0, 2, 4, 3]))

In [8]:
trans_col,fr_transition = crosstab(y[1:], y[:-1], levels=([0,1,2,3,4],[0,1,2,3,4]))
fr_transition

array([[3, 0, 0, 0, 1],
       [1, 2, 0, 0, 0],
       [1, 1, 6, 0, 0],
       [0, 0, 1, 4, 1],
       [0, 0, 1, 1, 3]])

In [9]:
trans_col

[[0, 1, 2, 3, 4], [0, 1, 2, 3, 4]]